server:
  port: 8081 # Server port for application

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource # Specify the type of datasource
    driver-class-name: com.mysql.cj.jdbc.Driver # Specify the JDBC driver
    # Database connection URL assembled from components
    url: jdbc:mysql://${datasource.host}:${datasource.port}/${datasource.dbname}?${datasource.parameters}
    username: ${datasource.username}
    password: ${datasource.password}


# Definitions of database connection components (to be provided by the customer)
datasource:
  host: gz-cynosdbmysql-grp-6gv2ivx1.sql.tencentcdb.com  # Database server host
  port: 28255 # Database server port
  dbname: COMP5703 # Database name
  parameters: characterEncoding=utf-8&useSSL=false # Connection parameters for the database
  username: Bill  #Username for database access
  password: Elec630M  # Password for database access
